### ISSUE TITLE
TODO for tomarrow

### ISSUE THREAD

**Issue by TwinIsland** [TwinIsland/unimp-checker#1]
- [x] add purning for sink: if a struct flow into k8s library call, taint all its fields. 
- [ ] redefine source: need some hack, `StructLit` might help
- [ ] override `pp()` for sink, to show the full struct path

**Comment by TwinIsland** [comment]
mark: https://github.com/github/codeql/issues/17134
